# Generated by Django 3.2.3 on 2021-06-05 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.cohort'),
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.team'),
        ),
        migrations.AlterField(
            model_name='student',
            name='vertical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.vertical'),
        ),
    ]
