# Generated by Django 3.2.3 on 2021-06-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_vertical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.cohort'),
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.team'),
        ),
        migrations.AlterField(
            model_name='student',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.vertical'),
        ),
    ]
